InventoryV1.Web/Models/Batch/BatchIndexViewModel.cs
using InventoryV1.Web.Models.Item;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryV1.Web.Models.Batch
{
    public class BatchIndexViewModel
    {
        public int Id { get; set; }
        public string GoodsReceivedNote { get; set; }
        public DateTime ExpiryDate { get; set; }

        //public int ItemId { get; set; }
        public ItemListingViewModel Item { get; set; }
    }
}

InventoryV1.Web/Models/Batch/BatchListingViewModel.cs
using InventoryV1.Web.Models.Item;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryV1.Web.Models.Batch
{
    public class BatchListingViewModel
    {
        public int Id { get; set; }
        public string GoodsReceivedNote { get; set; }
        public DateTime ExpiryDate { get; set; }

        public ItemListingViewModel Item { get; set; }
    }
}

InventoryV1.Web/Models/ErrorViewModel.cs
using System;

namespace InventoryV1.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InventoryV1.Web/Models/Item/ItemBatchViewModel.cs
using InventoryV1.Web.Models.Batch;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryV1.Web.Models.Item
{
    public class ItemBatchViewModel
    {
        public ItemListingViewModel Item { get; set; }
        public IEnumerable<BatchListingViewModel> Batches { get; set; }
    }
}

InventoryV1.Web/Models/Item/ItemDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryV1.Web.Models.Item
{
    public class ItemDetailViewModel
    {
        public int Id { get; set; }
        public string PartNumber { get; set; }
        public string ItemDescription { get; set; }
        public bool IsActive { get; set; }

        public ItemListingViewModel Item { get; set; }
    }
}

InventoryV1.Web/Models/Item/ItemIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryV1.Web.Models.Item
{
    public class ItemIndexViewModel
    {
        public IEnumerable<ItemListingViewModel> ItemList { get; set; }
    }
}

InventoryV1.Web/Models/Item/ItemListingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryV1.Web.Models.Item
{
    public class ItemListingViewModel
    {
        public int Id { get; set; }
        public string PartNumber { get; set; }
        public string ItemDescription { get; set; }
    }
}

InventoryV1.Web/Controllers/BatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InventoryV1.Service.Interfaces;
using InventoryV1.Web.Models.Batch;
using Microsoft.AspNetCore.Mvc;

namespace InventoryV1.Web.Controllers
{
    public class BatchController : Controller
    {
        private readonly IBatchService _batchService;

        public BatchController(IBatchService batchService)
        {
            _batchService = batchService;
        }

        public IActionResult Index(int id)
        {
            var batch = _batchService.GetById(id);

            var model = new BatchIndexViewModel
            {
                Id = batch.Id,
                GoodsReceivedNote = batch.GoodsReceivedNote,
                ExpiryDate = batch.ExpiryDate,
                //Item = batch.Item.PartNumber

            };

            return View(model);
        }
    }
}

InventoryV1.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InventoryV1.Web.Models;

namespace InventoryV1.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InventoryV1.Web/Controllers/ItemController.cs
using InventoryV1.Data.Entities;
using InventoryV1.Service.Interfaces;
using InventoryV1.Web.Models.Batch;
using InventoryV1.Web.Models.Item;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace InventoryV1.Web.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemService _itemService;
        private readonly IBatchService _batchService;

        public ItemController(IItemService itemService)
        {
            _itemService = itemService;
        }

        public IActionResult Index()
        {
            var items = _itemService.GetAll()
                .Select(item => new ItemListingViewModel
                {
                    Id = item.Id,
                    PartNumber = item.PartNumber,
                    ItemDescription = item.ItemDescription
                });

            var model = new ItemIndexViewModel
            {
                ItemList = items
            };

            return View(model);
        }
        
        /*
        public IActionResult Detail(int id)
        {
            var items = _itemService.GetById(id)
                .Select(item => new ItemDetailViewModel
                 {
                     Id = item.Id,
                     PartNumber = item.PartNumber,
                     ItemDescription = item.ItemDescription
                     IsActive = item.IsActive
                 });

            var model = new ItemIndexViewModel
            {
                ItemList = items
            };

            return View(model);
        } */

        public IActionResult Batch(int id)
        {
            var item = _itemService.GetById(id);
            var batches = item.Batches;

            var batchListings = batches.Select(batch => new BatchListingViewModel
            {
                Id = batch.Id,
                GoodsReceivedNote = batch.GoodsReceivedNote,
                ExpiryDate = batch.ExpiryDate,
                Item = BuildItemListing(batch)
            });

            var model = new ItemBatchViewModel
            {
                Batches = batchListings,
                Item = BuildItemListing(item)

            };

            return View(model);
        }

        private ItemListingViewModel BuildItemListing(Batch batch)
        {
            var item = batch.Items;
            return BuildItemListing(item);

        }

        private ItemListingViewModel BuildItemListing(Item item)
        {
            return new ItemListingViewModel
            {
                Id = item.Id,
                PartNumber = item.PartNumber,
                ItemDescription = item.ItemDescription
            };
        }
    }
}

InventoryV1.Web/Views/Batch/Index.cshtml
@model InventoryV1.Web.Models.Batch.BatchIndexViewModel

<h1>@Model.Item</h1>

<div>
    GRN: @Model.GoodsReceivedNote
</div>
<div>
    Expiry Date: @Model.ExpiryDate
</div>

InventoryV1.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InventoryV1.Web/Views/Item/Batch.cshtml
@model InventoryV1.Web.Models.Item.ItemBatchViewModel

<h1>Part Number: @Model.Item.PartNumber</h1>

@if (Model.Batches.Any()) 
{
    <table class="table table-bordered table-hover">
        <tbody>
            @foreach(var batch in Model.Batches) 
            {
            <tr>
                <td>
                    <a asp-controller="Batch" asp-action="Index" asp-route-id="@batch.Id">
                        @batch.GoodsReceivedNote
                    </a>
                </td>
                <td>
                    @batch.ExpiryDate
                </td>
            </tr>
            }
        </tbody>
    </table>
}
else{
    <div class="noBatches">
        <h3>
            No Data Available
            <a asp-controller="Batch" asp-action="Create" asp-route-id="@Model.Item.Id">
            <span>Create</span>
            </a>
        </h3>
    </div>
}

InventoryV1.Web/Views/Item/Index.cshtml
@model InventoryV1.Web.Models.Item.ItemIndexViewModel

<h1>Items</h1>

<table class="table table-hover" id="itemIndexTable">
    <tbody>
        @foreach (var item in Model.ItemList)
        {
        <tr>
            <td>
                <a asp-controller ="Item" asp-action="Batch" asp-route-id="@item.Id">
                    @item.PartNumber
                </a>
            </td>
            <td>
                @item.ItemDescription
            </td>
        </tr>
        }
    </tbody>
</table>

InventoryV1.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryV1.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InventoryV1.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - InventoryV1.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>